# Generated by Django 5.2.1 on 2025-06-10 22:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades del empleado',
                'ordering': ['habilidad'],
                'unique_together': {('habilidad',)},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('trabajo', models.CharField(choices=[('0', 'Contador'), ('1', 'Administrativo'), ('2', 'Desarrollador'), ('3', 'Analista Funcional'), ('4', 'Otro')], max_length=1, verbose_name='Puesto')),
                ('observaciones', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('habilidades', models.ManyToManyField(to='empleado.habilidades')),
                ('pais', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.pais')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
                'unique_together': {('nombre', 'apellido')},
            },
        ),
    ]
