# Generated by Django 5.2.1 on 2025-06-10 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.CharField(blank=True, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(blank=True, max_length=20, verbose_name='Rol')),
                ('habilidadesRol', models.ManyToManyField(to='empleado.habilidades')),
            ],
            options={
                'verbose_name': 'Rol/Trabajo',
                'verbose_name_plural': 'Roles/Trabajos',
                'ordering': ['nombreRol'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.rol'),
        ),
    ]
