# Generated by Django 5.2.1 on 2025-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('sigla', models.CharField(max_length=30, verbose_name='Sigla')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Está activo?')),
                ('piso', models.CharField(blank=True, max_length=5, verbose_name='Piso')),
                ('oficina', models.CharField(blank=True, max_length=10, verbose_name='Oficina N°')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Área de la empresa',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'sigla')},
            },
        ),
    ]
