# Generated by Django 5.2.3 on 2025-06-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='¿Estamo activo papi?'),
        ),
    ]
